sudo: required

services:
  - docker

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=ubuntu/trusty
  - TRAVIS_DEBIAN_DISTRIBUTION=ubuntu/xenial
  - TRAVIS_DEBIAN_DISTRIBUTION=ubuntu/yakkety

script:
  - wget -O- https://george-hopkins.github.io/travis-ubuntu/script.sh | sh -
